// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SmssApi
{
    public partial class SmsMessage
    {
        public Guid Id { get; set; }
        public int UserId { get; set; }
        public string From { get; set; }
		public string Content { get; set; }
		public virtual User User { get; set; }
		public virtual ICollection<SmsStatus> SmsStatuses { get; set; }

	}
}